name: CI + Publish

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore src/Philiprehberger.WebhookSignature.csproj
      - run: dotnet build src/Philiprehberger.WebhookSignature.csproj --configuration Release --no-restore
      - run: dotnet test tests/Philiprehberger.WebhookSignature.Tests/Philiprehberger.WebhookSignature.Tests.csproj --configuration Release --no-restore

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
      - run: dotnet pack src/Philiprehberger.WebhookSignature.csproj --configuration Release -o out
      - run: dotnet nuget push out/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
